/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.palashmax


class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
    /*ServerEndpointConfig.Builder.create(SocketEndpoint::class.java, "/display")
        .configurator(ServerEndpointConfig.Configurator())
        .build()*/
    // TODO: Embedded Glassfish Server
    /*if(args.isNotEmpty() && args[0] == "server") {
        DesktopCaptureServer().createWebSocketServer()
    } else {
        DisplayStreamerClient().launchApp()
    }*/
    DesktopCaptureServer().createSocketServer()
}
